### ISSUE TITLE
Popup error notification when opening git changes editor window

### ISSUE THREAD

**Issue by serg3295** [carlthome/vscode-git-line-blame#30]
Reproduce:
Timeline -> right click on a file 'Open Changes' ->
![blame_err1](https://github.com/carlthome/vscode-git-line-blame/assets/75196080/1269e317-5b6c-45ec-8e8a-b42c575b8ec4)

**Comment by carlthome** [comment]
Thanks for raising this @serg3295! 🥇 

And thanks for pointing to a fix @dereli! 👏 

I've been a bit confused as to how one can access the editor within the event handler.

Since both `vscode.window.onDidChangeTextEditorSelection` and `vscode.window.onDidChangeTextEditorVisibleRanges` receive a TextEditor, it's easier to avoid accessing `vscode.window.activeTextEditor` in the event handler. Fix incoming: https://github.com/carlthome/vscode-git-line-blame/pull/31

**Comment by serg3295** [comment]
Thanks!
